# some useful alias
alias gcd='cd /c/Users/`whoami`/git'

alias ga='git add'
alias gaa='git add .'
alias gaaa='git add --all'
alias gs='git status'
alias gcm='git commit -m'
alias gcma='git commit -a -m'
alias gbr='git branch'
alias gco='git checkout'
alias gdf='git diff'
alias gls='git ls-files'
alias gsh='git stash'
alias gsha='git stash apply'
alias gshp='git stash pop'
alias gshl='git stash list'
alias gmg='git merge'
alias gph='git push -u'
